export enum Icon {
  CALENDAR_MONTH = 'calendar_month',
  NO_FOOD = 'no_food',
  HOME = 'home',
  SEARCH = 'search',
  SHOPPING_BASKET = 'shopping_basket',
  FRIDGE = 'kitchen',
  BULB = 'lightbulb',
  CONTACT = 'contact_phone',
  PHOTO_CAMERA = 'photo_camera',
  ARROW_BACK = 'arrow_back',
  ARROW_FRONT = 'chevron_right',
  CHECK = 'check',
  LOGOUT = 'logout',
  ADD = 'add',
  PUBLISH = 'publish',
  END_CALENDAR = 'event_busy',
  MORE_HORIZ = 'more_horiz',
  LOCK_OPEN = 'lock_open',
  EDIT = 'edit',
  DELETE = 'delete',
}
